name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: pip install --upgrade pip
      working-directory: .  # Use this if your requirements.txt is in the root directory

    - name: Run tests
      run: python -m unittest discover -s . -p "*_test.py"
